backend/controllers/SettingsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Settings;
use common\models\SettingsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SettingsController implements the CRUD actions for Settings model.
 */
class SettingsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'flush-cache' => ['post']
                ],
            ],
            'rateLimiter' => ['class' => 'yii\filters\RateLimiter'],
        ];
    }

    /**
     * Lists all Settings models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SettingsSearch();
        //$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        $rows = (new \yii\db\Query())
            ->select(['key', 'value'])
            ->from('settings')
            ->indexBy('key')
            ->all();
        
        $data = [];
        foreach(Settings::getValues('keys') as $key => $val) {
            if(!isset($val['group'])) {
                $val['group'] = $searchModel::defaultGroup;
            }
            if(!isset($data[$val['group']])) {
                $data[$val['group']] = [];
            }
            $data[$val['group']][$key] = array_merge(['key' => $key, 'value' => (isset($rows[$key]) ? $rows[$key]['value'] : (isset($val['defaultValue']) ? $val['defaultValue'] : null))], $val); 
            unset($rows[$key]);
        }
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'data' => $data,
            'unused' => $rows
        ]);
    }

    /**
     * Displays a single Settings model.
     * @param string $id
     * @return mixed
     */
    /*public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }*/

    /**
     * Creates a new Settings model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    /*public function actionCreate()
    {
        $model = new Settings();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->key]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }*/

    /**
     * Updates an existing Settings model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    /*public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->key]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }*/

    /**
     * Deletes an existing Settings model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionEdit($id) {
        if(($key = Settings::getValue('keys', $id)) === null) {
            throw new \yii\base\InvalidParamException('Nieprawidłowy klucz ustawień.');
        }
        
        try {
            $model = $this->findModel($id);
        } catch (NotFoundHttpException $ex) {
            $model = new Settings();
            $model->key = $id;
            if(isset($key['defaultValue'])) {
                $model->value = $key['defaultValue'];
            }
        }
        
        if(isset($key['events'])) {
            foreach($key['events'] as $name => $event) {
                $model->on($name, $event, $key);
            }
        }
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('edit', [
                'model' => $model,
                'key' => $key
            ]);
        }
    }

    public function actionFlushCache() {
        if(Yii::$app->cache->flush()) {
            Yii::$app->session->addFlash('success', 'Poprawnie wyczyszczono pamięć podręczną.');
        } else {
            Yii::$app->session->addFlash('error', 'Nie udało się wyczyszcić pamięci podręcznej.');
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the Settings model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Settings the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Settings::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use common\models\UserSearch;
use backend\models\PermissionForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'allow' => false,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'rateLimiter' => ['class' => 'yii\filters\RateLimiter'],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Nowy użytkownik został utworzony. Na podany adres email został wysłany mail z instrukcją do zalogowania. Pamiętaj, że użytkownik <b>nie będzie mógł się zalogować</b> na swoje konto dopóki nie utrzyma <b>odpowiednich uprawnień</b>!');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function actionPermissions($id) {
        $user = $this->findModel($id);
        $model = new PermissionForm();
        
        if($model->load(Yii::$app->request->post()) && $model->assign($user)) {
            Yii::$app->session->addFlash('success', 'Poprawnie zmieniono uprawnienia użytkownika.');
            return $this->redirect(['view', 'id' => $user->id]);
        } else {
            $roles = Yii::$app->authManager->getRolesByUser($user->id);
            foreach($roles as $role) {
                $model->roles[] = $role->name;
            }
        }
        
        return $this->render('permission', [
            'model' => $model,
            'user' => $user
        ]);
    }
    
    /* public function actionList($q = '', $page = 1) {
        Yii::$app->response->format = 'json';
        
        $query = User::find()
                ->select(['id', 'username AS text'])
                ->filterWhere(['like', 'username', $q])
                // ->indexBy('id')
                ->asArray()
                ->limit(Yii::$app->params['listQueryDefaultPageSize'])
                ->offset(($page - 1) * Yii::$app->params['listQueryDefaultPageSize'])
                ->all();
        
        return ['results' => $query];
    } */
}

backend/views/layouts/main.php
<?php
use backend\assets\AppAsset;
use gandh1pl\helpers\Html;
use gandh1pl\helpers\Breadcrumbs;
use gandh1pl\helpers\Alert;
use gandh1pl\adminlte\Nav;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
$counters = Yii::$app->cacheHelper->get('counters');

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title>Panel administracyjny - <?= Yii::$app->name ?></title>
    <?php $this->head() ?>
</head>
<body class="skin-green sidebar-mini">
    <?php $this->beginBody() ?>
     <div class="wrapper">
      <header class="main-header">
        <!-- Logo -->
		<?= Html::a('<span class="logo-mini">'.Html::img('@www/favicon.png', ['width'=>'32', 'height'=>'32']).'</span><span class="logo-lg"><b>'.Yii::$app->name.'</b></span>', 
			['site/index'],
			['class'=>'logo']
		) ?>
		
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <?= Html::a(Html::img('@www/favicon.png', ['class' => 'user-image', 'alt' => 'User image'])
                            . Yii::$app->user->identity->username, '#', [
                            'class' => 'dropdown-toggle',
                            'data-toggle' => 'dropdown'
                        ]) ?>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <?= Html::img('@www/images/logo.png', ['class' => 'img-circle', 'alt' => 'User image']) ?>
                                <p>
                                    <?= Yii::$app->user->identity->username ?>
                                    <small>Konto od <?= Yii::$app->formatter->asDatetime(Yii::$app->user->identity->created_at, 'MMM Y') ?></small>
                                </p>
                            </li>
                            <li class="user-body"></li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <p>Uprawnienia:</p>
                                    <?php $roles = Yii::$app->authManager->getRolesByUser(Yii::$app->user->id);
                                    if(empty($roles)): ?>
                                    <p class="text-danger">Brak uprawnień!</p>
                                    <?php else: foreach($roles as $role): ?>
                                    <p><span class="label label-primary"><?= $role->description ?></span></p>
                                    <?php endforeach; endif; ?>
                                </div>
                                <div class="pull-right">
                                    <?= Html::a('Wyloguj', ['/site/logout'], ['class' => 'btn btn-default btn-flat', 'icon' => 'off', 'data-method' => 'post']) ?>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
      </header>

      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
				&nbsp;
            </div>
            <div class="pull-left info">
				<?php if(Yii::$app->user->isGuest): ?>
					<p>Niezalogowany</p>
				<?php else: ?>
					<p><?= Yii::$app->user->identity->username ?></p>
					<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
				<?php endif; ?>
            </div>
          </div>
          <!-- search form -->
          <!-- <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search..." />
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form> -->
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <?php
          $isLogged = !Yii::$app->user->isGuest;
          echo Nav::widget([
              'items' => [
                  ['label' => 'Zaloguj', 'url' => ['site/login'], 'visible' => !$isLogged, 'icon' => 'unlock', 'itemActiveCheckingSimple' => false],
                  ['label' => 'Strona domowa', 'url' => ['site/index'], 'visible' => $isLogged, 'icon' => 'fa-dashboard', 'itemActiveCheckingSimple' => false],
                  ['label' => 'System', 'url' => '#', 'visible' => $isLogged && Yii::$app->user->can('admin'), 'icon' => 'fa-cogs', 'items' => [
                      ['label' => 'Użytkownicy', 'url' => ['user/index'], 'icon' => 'fa-user', 'badge' => [$counters['users'], '']],
                      // ['label' => Yii::t('backend', 'Content management'), 'url' => ['content/index'], 'icon' => 'list-alt'],
                      ['label' => 'Ustawienia', 'url' => ['settings/index'], 'icon' => 'fa-cog'],
                  ]],
                  ['label' => 'Wyloguj się', 'url' => ['site/logout'], 'visible' => $isLogged, 'icon' => 'fa-lock', 'linkOptions' => ['data-method' => 'post'], 'itemActiveCheckingSimple' => false],
              ],
              'itemActiveCheckingSimple' => true,
              'options' => [
                  'class' => 'sidebar-menu',
              ]
          ]) ?>
        </section>
        <!-- /.sidebar -->
      </aside>

		<div class="content-wrapper">
			<section class="content-header">
				<?= Breadcrumbs::widget([
					'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    'options' => ['class' => 'breadcrumb']
				]) ?>
				<h1><?= (isset($this->params['content-header']) ? $this->params['content-header'] : /*'&nbsp;'*/ '<small>'.$this->title.'</small>') ?></h1>
                <div class="clearfix"></div>
			</section>
			<section class="content">
				<?= Alert::widget([
                    			'closeButton' => false,
                ]) 		?>
				<?php
					if(!isset($this->params['content-box']) || $this->params['content-box'] !== false): 
				?><div class="box">
					<div class="box-body">
						<?= $content ?>
					</div>
				</div><?php else: 
					echo $content;
				endif; ?>
			</section>
		</div>
    </div>

	<footer class="main-footer">
		<div class="pull-right hidden-xs">
			<?= Yii::powered() ?>
		</div>
		&copy; <?= Yii::$app->name ?> <?= date('Y') ?>
	</footer>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/simple.php
<?php
use backend\assets\AppAsset;
use gandh1pl\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= $this->title ?> - <?= Yii::$app->name ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">
    <?php $this->beginBody() ?>
    <?= $content ?>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>