common/models/Settings.php
<?php

namespace common\models;

use Yii;
use gandh1pl\helpers\ActiveRecord;
use common\widgets\LogActionBehavior;

/**
 * This is the model class for table "settings".
 *
 * @property string $key
 * @property string $value
 */
class Settings extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'settings';
    }
    
    public static $defaultGroup = 'others';
    
    public static function values() {
        return [
            'groups' => [
                'contact' => 'Kontakt',
                'users' => 'Użytkownicy',
                'system' => 'System',
                'others' => 'Inne ustawienia',
            ],
            'keys' => [
                'contactEmail' => [
                    'description' => 'Kontaktowy adres email',
                    'validation' => 'yii\validators\EmailValidator',
                    'group' => 'contact'
                ],
                'facebook-page' => [
                    'description' => "Link do strony na facebook'u",
                    'validation' => 'yii\validators\UrlValidator',
                    'hint' => 'Nie zapomnij o protokole na początku (https://)',
                    'group' => 'contact'
                ],
                // 
                'userLoginAttempsVerification' => [
                    'description' => 'Liczba nieudanych logowań, po których wymagany będzie kod weryfikacyjny.',
                    'defaultValue' => 3,
                    'group' => 'users',
                    'validation' => 'integer'
                ],
                //
                'siteName' => [
                    'description' => 'Nazwa strony',
                    'defaultValue' => 'Yii2lte',
                    'group' => 'system',
                ],
                'metaDescription' => [
                    'description' => 'Opis meta strony (dla wyszukiwarek - krótki opis co się znajduje na stronie)',
                    'group' => 'system'
                ],
                'metaKeywords' => [
                    'description' => 'Słowa kluczowe strony (lista słów, które najlepiej opisują treść strony, oddzielone przecinkami)',
                    'group' => 'system'
                ],
                'googleAnalytics' => [
                    'description' => 'Identyfikator Google Analytics',
                    'hint' => 'Jeśli chcesz używać statystyk Google Analytics, podaj tutaj identyfikator wygenerowany na stronie <a href="https://www.google.com/intl/pl_pl/analytics/" target="_blank">Google Analytics</a>.',
                    'group' => 'system'
                ],
                'cacheDefaultDuration' => [
                    'description' => 'Domyślny czas przechowywania pamięci podręcznej (w sekundach)',
                    'defaultValue' => 86400,
                    'group' => 'system',
                    'validation' => 'integer'
                ],
                'rateLimit' => [
                    'description' => 'Max. ilość żądań HTTP w danym okresie czasu',
                    'defaultValue' => 3,
                    'group' => 'system',
                    'validation' => 'integer'
                ],
                'rateLimitPeriod' => [
                    'description' => 'Okres czasu, w którym będą zliczane żądania HTTP (w sekundach)',
                    'defaultValue' => 1,
                    'group' => 'system',
                    'validation' => 'integer'
                ],
            ],
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['key', 'value'], 'required'],
            [['key'], 'string', 'max' => 50],
            [['value'], 'string', 'max' => 255],
            [['value'], 'validateValue']
        ];
    }
    
    public function validateValue($attr, $params) {
        if(($options = Settings::getValue('keys', $this->key)) === null) {
            return $this->addError('key', 'Nieprawidłowy klucz - wybierz z listy jakie ustawienie chcesz zmienić.');
        }
        if(isset($options['validation'])) {
            $validator = null;
            if(is_string($options['validation'])) {
                $validator = \yii\validators\Validator::createValidator($options['validation'], $this, $attr);
            } elseif(is_array($options['validation'])) {
                $validator = Yii::createObject($options['validation']['class'], $options['validation']);
            }
            $error = null;
            if($validator && !$validator->validate($this->value, $error)) {
                $this->addError('value', $error);
            }
        }
    }
    
    public function getDescription() {
        return static::$keys[$this->key]['description'];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'key' => 'Klucz',
            'value' => 'Wartość',
            'description' => 'Opis wartości'
        ];
    }
    
    public function afterSave($insert, $changedAttributes) {
        parent::afterSave($insert, $changedAttributes);
        
        Yii::$app->cache->delete('cache_settings');
    }
    
    public function afterDelete() {
        parent::afterDelete();
        
        Yii::$app->cache->delete('cache_settings');
    }
}

backend/controllers/SettingsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Settings;
use common\models\SettingsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SettingsController implements the CRUD actions for Settings model.
 */
class SettingsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'flush-cache' => ['post']
                ],
            ],
            'rateLimiter' => ['class' => 'yii\filters\RateLimiter'],
        ];
    }

    /**
     * Lists all Settings models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SettingsSearch();
        //$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        $rows = (new \yii\db\Query())
            ->select(['key', 'value'])
            ->from('settings')
            ->indexBy('key')
            ->all();
        
        $data = [];
        foreach(Settings::getValues('keys') as $key => $val) {
            if(!isset($val['group'])) {
                $val['group'] = $searchModel::defaultGroup;
            }
            if(!isset($data[$val['group']])) {
                $data[$val['group']] = [];
            }
            $data[$val['group']][$key] = array_merge(['key' => $key, 'value' => (isset($rows[$key]) ? $rows[$key]['value'] : (isset($val['defaultValue']) ? $val['defaultValue'] : null))], $val); 
            unset($rows[$key]);
        }
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'data' => $data,
            'unused' => $rows
        ]);
    }

    /**
     * Displays a single Settings model.
     * @param string $id
     * @return mixed
     */
    /*public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }*/

    /**
     * Creates a new Settings model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    /*public function actionCreate()
    {
        $model = new Settings();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->key]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }*/

    /**
     * Updates an existing Settings model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    /*public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->key]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }*/

    /**
     * Deletes an existing Settings model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionEdit($id) {
        if(($key = Settings::getValue('keys', $id)) === null) {
            throw new \yii\base\InvalidParamException('Nieprawidłowy klucz ustawień.');
        }
        
        try {
            $model = $this->findModel($id);
        } catch (NotFoundHttpException $ex) {
            $model = new Settings();
            $model->key = $id;
            if(isset($key['defaultValue'])) {
                $model->value = $key['defaultValue'];
            }
        }
        
        if(isset($key['events'])) {
            foreach($key['events'] as $name => $event) {
                $model->on($name, $event, $key);
            }
        }
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('edit', [
                'model' => $model,
                'key' => $key
            ]);
        }
    }

    public function actionFlushCache() {
        if(Yii::$app->cache->flush()) {
            Yii::$app->session->addFlash('success', 'Poprawnie wyczyszczono pamięć podręczną.');
        } else {
            Yii::$app->session->addFlash('error', 'Nie udało się wyczyszcić pamięci podręcznej.');
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the Settings model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Settings the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Settings::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/settings/_form.php
<?php

use gandh1pl\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model common\models\Settings */
/* @var $form yii\widgets\ActiveForm */
/* @var $key array */

$description = ArrayHelper::getValue($key, 'description', '');
$hint = ArrayHelper::getValue($key, 'hint', '');

$fieldConfig = ArrayHelper::getValue($key, 'fieldConfig', [
    'function' => 'textInput',
    'params' => [
        ['maxlength' => true],
    ]
]);

if($fieldConfig instanceof \Closure) {
    $fieldConfig = $fieldConfig($model, $key);
}

?>

<div class="settings-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'key')->dropDownList([$model->key => $description], ['disabled' => 'disabled']) ?>
    
    <p class="text-muted"><?= $hint ?></p>

    <?= call_user_func_array([$form->field($model, 'value'), $fieldConfig['function']], $fieldConfig['params']) ?>

    <div class="form-group">
        <?= Html::a('Powrót', ['settings/index'], ['class' => 'btn btn-primary', 'icon' => 'arrow-left']) ?>
        <?= Html::submitButton('Zapisz', ['class' => 'btn btn-success', 'icon' => 'edit']) ?>
        <?php 
            if(!$model->isNewRecord) {
                echo Html::a('Wyczyść', ['settings/delete', 'id' => $model->key], ['class' => 'btn btn-danger', 'icon' => 'remove', 'data-method' => 'post', 'data-confirm' => 'Czy jesteś pewny, że chcesz wyczyścić tą wartość?']);
            }
        ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

backend/views/settings/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\SettingsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="settings-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'key') ?>

    <?= $form->field($model, 'value') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/settings/create.php
<?php

use gandh1pl\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Settings */

$this->title = 'Create Settings';
$this->params['breadcrumbs'][] = ['label' => 'Settings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="settings-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/settings/edit.php
<?php

use gandh1pl\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Settings */
/* @var $key array */

$this->title = 'Zmień ustawienia';

$this->params['breadcrumbs'][] = ['label' => 'Ustawienia', 'icon' => 'fa-cogs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $this->title, 'icon' => 'edit', 'url' => '#'];
?>
<div class="settings-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'key' => $key
    ]) ?>

</div>

backend/views/settings/index (copy 1).php
<?php

use gandh1pl\helpers\Html;
use yii\grid\GridView;
use common\models\Settings;
use yii\data\ArrayDataProvider;
use common\widgets\adminlte\Box;

/* @var $this yii\web\View */
/* @var $searchModel common\models\SettingsSearch */
/* @var $data array */
/* @var $unused Array */

$this->title = 'Ustawienia';

$this->params['breadcrumbs'][] = ['label' => $this->title, 'icon' => 'fa-cogs', 'url' => '#'];

$blocks = [
    [], []
];
$i = 0;
?>
<div class="settings-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row"><?php foreach($data as $group => $arr): ?>
        <?php $this->beginBlock('setting-' . $group); ?>
            <div class="panel panel-primary">
                <div class="panel-heading"><?=
                    Html::a(Settings::getValue('groups', $group), '#collapse-' . $group, ['data-toggle' => 'collapse', 'icon' => 'resize-vertical'])
                ?></div>
                <div id="collapse-<?= $group ?>" class="panel-collapse collapse in">
                    <div class="panel-body">
                    <?= GridView::widget([
                        'dataProvider' => new ArrayDataProvider([
                            'allModels' => $arr
                        ]),
                        //'filterModel' => $searchModel,
                        'columns' => [
                            // ['class' => 'yii\grid\SerialColumn'],

                            ['attribute' => 'description', 'label' => 'Opis', 'format' => 'html', 'value' => function($model) { return Html::a($model['description'], ['edit', 'id' => $model['key']]); }],
                            ['attribute' => 'value', 'label' => 'Wartość', 'format' => 'raw', 'value' => function($model) {
                                if(isset($model['truncate'])) {
                                    return \yii\helpers\StringHelper::truncateWords($model['value'], $model['truncate'], '...', true);
                                } else if(isset($model['columnFormat'])) {
                                    if($model['columnFormat'] instanceof \Closure) {
                                        return call_user_func($model['columnFormat'], $model);
                                    } else if(($func = Settings::getValue('columnFormat', $model['columnFormat'])) instanceof \Closure) {
                                        return call_user_func($func, $model);
                                    }
                                    return Yii::$app->formatter->format($model['value'], $model['columnFormat']);
                                }
                                return $model['value'];
                            }],

                        ],
                        'layout' => "{items}\n{pager}",
                        'options' => ['class' => 'table-responsive'],
                    ]); ?>
                    </div>
                </div>
            </div>
        <?php $this->endBlock(); 
        $blocks[$i++][] = $this->blocks['setting-'.$group];
        if($i > 1) { $i = 0; }
        endforeach;
        ?>
        <div class="col-xs-12 col-md-6"><?php
            foreach($blocks[0] as $block) {
                echo $block;
            }
        ?></div>
        <div class="col-xs-12 col-md-6"><?php
            foreach($blocks[1] as $block) {
                echo $block;
            }
        ?></div>
    </div> <!-- row -->
    <?php
        /*if(!empty($unused)) {
            echo '<hr/><div class="alert alert-warning">'.
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'.
                Html::icon('wrench') . ' <b>Uwaga!</b> Istnieje <b>' . count($unused) . '</b> nieużywanych ustawień w bazie danych!'
            .'</div>';
        }*/
    ?>
</div>

backend/views/settings/index.php
<?php

use gandh1pl\helpers\Html;
use yii\grid\GridView;
use common\models\Settings;
use yii\data\ArrayDataProvider;
use yii\jui\JuiAsset;

JuiAsset::register($this);

/* @var $this yii\web\View */
/* @var $searchModel common\models\SettingsSearch */
/* @var $data array */
/* @var $unused Array */

$this->title = 'Ustawienia';
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => '#', 'icon' => 'fa-cogs'];

$blocks = [
    [], []
];
$i = 0;
?>
<div class="settings-index">

    <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
    <div class="form-group pull-right">
        <?= Html::a('Wyczyść pamięć podręczną', ['flush-cache'], ['class' => 'btn btn-danger', 'icon' => 'trash', 'data-confirm' => 'Czy jesteś pewien, że chcesz to zrobić?', 'data-method' => 'post']) ?>
    </div>
    <div class="clearfix"></div>
    <div class="row"><?php foreach($data as $group => $arr): if(empty($arr)) continue; ?>
        <?php $this->beginBlock('setting-' . $group); ?>
            <div class="panel panel-primary" id="block-<?= $group ?>">
                <div class="panel-heading"><?=
                    Html::a(Settings::getValue('groups', $group), '#collapse-' . $group, ['data-toggle' => 'collapse', 'icon' => 'resize-vertical'])
                ?></div>
                <div id="collapse-<?= $group ?>" class="panel-collapse collapse in">
                    <div class="panel-body">
                    <?= GridView::widget([
                        'dataProvider' => new ArrayDataProvider([
                            'allModels' => $arr
                        ]),
                        //'filterModel' => $searchModel,
                        'columns' => [
                            // ['class' => 'yii\grid\SerialColumn'],

                            ['attribute' => 'description', 'label' => 'Opis', 'format' => 'html', 'value' => function($model) { return Html::a($model['description'], ['edit', 'id' => $model['key']]); }],
                            ['attribute' => 'value', 'label' => 'Wartość', 'format' => 'raw', 'value' => function($model) {
                                if(isset($model['truncate'])) {
                                    return \yii\helpers\StringHelper::truncateWords($model['value'], $model['truncate'], '...', true);
                                } else if(isset($model['columnFormat'])) {
                                    if($model['columnFormat'] instanceof \Closure) {
                                        return call_user_func($model['columnFormat'], $model);
                                    } else if(is_array($model['columnFormat'])) { 
                                        return isset($model['columnFormat'][$model['value']]) ? $model['columnFormat'][$model['value']] : Yii::$app->formatter->nullDisplay;
                                    } else if(($func = Settings::getValue('columnFormat', $model['columnFormat'])) instanceof \Closure) {
                                        return call_user_func($func, $model);
                                    }
                                    return Yii::$app->formatter->format($model['value'], $model['columnFormat']);
                                }
                                return $model['value'];
                            }],

                        ],
                        'layout' => "{items}\n{pager}",
                        'options' => ['class' => 'table-responsive'],
                    ]); ?>
                    </div>
                </div>
            </div>
        <?php $this->endBlock(); 
        $blocks[$i++][] = $this->blocks['setting-'.$group];
        if($i > 1) { $i = 0; }
        endforeach;
        ?>
        <div class="col-xs-12 col-md-6 connectedSortable columnLeft"><?php
            foreach($blocks[0] as $block) {
                echo $block;
            }
        ?></div>
        <div class="col-xs-12 col-md-6 connectedSortable columnRight"><?php
            foreach($blocks[1] as $block) {
                echo $block;
            }
        ?></div>
    </div> <!-- row -->
    <?php
        if(!empty($unused)) {
            echo '<hr/><div class="alert alert-warning">'.
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'.
                Html::icon('wrench') . ' <b>Uwaga!</b> Istnieje <b>' . count($unused) . '</b> nieużywanych ustawień w bazie danych!'
            .'</div>';
        }
        $this->registerJs('
            var sortable = $(".connectedSortable").sortable({
                placeholder: "sort-highlight",
                connectWith: ".connectedSortable",
                handle: ".panel-heading",
                forcePlaceholderSize: true,
                zIndex: 9999
            });
            sortable.find(".panel .panel-heading").css("cursor", "move");
            
            if(localStorage !== undefined) {
                sortable.on("sortupdate", function(event, ui) {
                    var sorted = $(this).sortable("toArray"),
                        target = $(event.target);
                    if(target.is(".columnLeft")) {
                        localStorage.setItem("settings-col-left", sorted);
                    } else {
                        localStorage.setItem("settings-col-right", sorted);
                    }
                });
                
                function sortColumn(id, ls_index) {
                    var positions = localStorage.getItem(ls_index);
                    if(positions !== null) {
                        var pos = positions.split(",");
                        for(var i = 0; i < pos.length; i++) {
                            $("#" + pos[i]).appendTo(id);
                        }
                    }
                }
                sortColumn(".columnLeft", "settings-col-left");
                sortColumn(".columnRight", "settings-col-right");
            }
            
        ');
    ?>
</div>

backend/views/settings/update.php
<?php

use gandh1pl\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Settings */

$this->title = 'Update Settings: ' . ' ' . $model->key;
$this->params['breadcrumbs'][] = ['label' => 'Settings', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->key, 'url' => ['view', 'id' => $model->key]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="settings-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/settings/view.php
<?php

use gandh1pl\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Settings */

$this->title = $model->key;
$this->params['breadcrumbs'][] = ['label' => 'Settings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="settings-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->key], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->key], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'description',
            'value',
        ],
    ]) ?>

</div>